### ISSUE TITLE
Pathway export saves pathways as "New Pathway"

### ISSUE THREAD

**Issue by cannin** [iVis-at-Bilkent/pathway-mapper#69] opened 2017-02-08 19:42 UTC
All the pathways I've tried to export to txt file from pathwaymapper.org have "New Pathway" listed on the first line rather than the actual name.

**Comment by ugurdogrusoz** [comment] 2017-02-09 05:58
Can you reproduce this @leonarddrv ? I can't.

**Comment by ugurdogrusoz** [comment] 2017-04-06 05:31
closing since we can't reproduce it

**Closed by ugurdogrusoz** 2017-04-06 05:31 UTC
